---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cve-operator
    control-plane: controller-manager
  name: cve-operator-controller-manager
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      imagePullSecrets:
        - name: registrypullsecret
      containers:
      - args:
        - --metrics-bind-address=:8443
        - --leader-elect
        - --health-probe-bind-address=:8081
        command:
        - /manager
        image: eashanroy7866/cve-operator:latest
        env:
          - name: cve_processor_container
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: cve_processor_container
          - name: cve_processor_image
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: cve_processor_image
          - name: namespace
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: namespace
          - name: image_pull_secret_name
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: image_pull_secret_name
          - name: kafka_host
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: kafka_host
          - name: kafka_port
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: kafka_port
          - name: kafka_topic
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: kafka_topic
          - name: monitor_from
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: monitor_from
          - name: reconciler_requeue
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: reconciler_requeue
          - name: github_token
            valueFrom:
              secretKeyRef:
                name: operator-secret
                key: github_token
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cve-operator-controller-manager
      terminationGracePeriodSeconds: 10
